// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Krateo Support",
            "url": "https://krateo.io",
            "email": "contact@krateoplatformops.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/{owner}/{repo}/branches/{branch}/protection": {
            "get": {
                "description": "Retrieves branch protection settings and normalizes the response for drift-free reconciliation.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get branch protection",
                "operationId": "get-branch-protection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository owner (user or organization)",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Repository name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Branch name",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/branchprotection.BranchProtectionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/branchprotection.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Creates or updates branch protection rules. Used for both create and update actions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create or update branch protection",
                "operationId": "put-branch-protection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository owner (user or organization)",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Repository name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Branch name",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Branch protection settings",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/branchprotection.BranchProtectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/branchprotection.BranchProtectionResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/branchprotection.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes branch protection rules. Idempotent: returns 204 even if branch was not protected.",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete branch protection",
                "operationId": "delete-branch-protection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repository owner (user or organization)",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Repository name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Branch name",
                        "name": "branch",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/branchprotection.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "branchprotection.BranchProtectionRequest": {
            "type": "object",
            "required": [
                "enforce_admins",
                "required_pull_request_reviews",
                "required_status_checks",
                "restrictions"
            ],
            "properties": {
                "allow_deletions": {
                    "description": "Allows deletion of the protected branch by anyone with write access to the repository. Set to false to prevent deletion of the protected branch. Default: false.",
                    "type": "boolean"
                },
                "allow_force_pushes": {
                    "description": "Permits force pushes to the protected branch by anyone with write access to the repository. Set to true to allow force pushes. Set to false or null to block force pushes. Default: false.",
                    "type": "boolean",
                    "x-nullable": true
                },
                "allow_fork_syncing": {
                    "description": "Whether users can pull changes from upstream when the branch is locked. Set to true to allow fork syncing. Set to false to prevent fork syncing. Default: false.",
                    "type": "boolean",
                    "default": false
                },
                "block_creations": {
                    "description": "If set to true, the restrictions branch protection settings which limits who can push will also block pushes which create new branches, unless the push is initiated by a user, team, or app which has the ability to push. Default: false.",
                    "type": "boolean"
                },
                "enforce_admins": {
                    "description": "Enforce all configured restrictions for administrators. Set to ` + "`" + `true` + "`" + ` to enforce required status checks for repository administrators. Set to ` + "`" + `null` + "`" + ` to disable.",
                    "type": "boolean",
                    "x-nullable": true
                },
                "lock_branch": {
                    "description": "Whether to set the branch as read-only. If this is true, users will not be able to push to the branch. Default: false.",
                    "type": "boolean",
                    "default": false
                },
                "required_conversation_resolution": {
                    "description": "Requires all conversations on code to be resolved before a pull request can be merged into a branch that matches this rule. Set to false to disable. Default: false.",
                    "type": "boolean"
                },
                "required_linear_history": {
                    "description": "Enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch. Set to true to enforce a linear commit history. Set to false to disable. Default: false.",
                    "type": "boolean"
                },
                "required_pull_request_reviews": {
                    "description": "Require at least one approving review on a pull request, before merging. Set to ` + "`" + `null` + "`" + ` to disable.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.RequiredPullRequestReviews"
                        }
                    ],
                    "x-nullable": true
                },
                "required_status_checks": {
                    "description": "Require status checks to pass before merging. Set to ` + "`" + `null` + "`" + ` to disable.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.RequiredStatusChecks"
                        }
                    ],
                    "x-nullable": true
                },
                "restrictions": {
                    "description": "Restrict who can push to the protected branch. User, app, and team restrictions are only available for organization-owned repositories. Set to null to disable.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.Restrictions"
                        }
                    ],
                    "x-nullable": true
                }
            }
        },
        "branchprotection.BranchProtectionResponse": {
            "type": "object",
            "properties": {
                "allow_deletions": {
                    "description": "Whether deletion of the protected branch is allowed.",
                    "type": "boolean"
                },
                "allow_force_pushes": {
                    "description": "Whether force pushes are permitted.",
                    "type": "boolean"
                },
                "allow_fork_syncing": {
                    "description": "Whether users can pull changes from upstream when the branch is locked.",
                    "type": "boolean"
                },
                "block_creations": {
                    "description": "Whether pushes that create new branches are blocked.",
                    "type": "boolean"
                },
                "enforce_admins": {
                    "description": "Whether admins are subject to the branch protection rules.",
                    "type": "boolean"
                },
                "lock_branch": {
                    "description": "Whether the branch is read-only.",
                    "type": "boolean"
                },
                "required_conversation_resolution": {
                    "description": "Whether all conversations on code must be resolved before merging.",
                    "type": "boolean"
                },
                "required_linear_history": {
                    "description": "Whether a linear commit Git history is enforced.",
                    "type": "boolean"
                },
                "required_pull_request_reviews": {
                    "description": "Pull request review requirements.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.RequiredPullRequestReviewsResponse"
                        }
                    ]
                },
                "required_status_checks": {
                    "description": "Require status checks to pass before merging.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.RequiredStatusChecks"
                        }
                    ]
                },
                "restrictions": {
                    "description": "Push access restrictions.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.Restrictions"
                        }
                    ]
                },
                "url": {
                    "description": "The URL of the branch protection resource.",
                    "type": "string"
                }
            }
        },
        "branchprotection.BypassAllowances": {
            "type": "object",
            "properties": {
                "apps": {
                    "description": "The list of app ` + "`" + `slug` + "`" + `s allowed to bypass pull request requirements.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teams": {
                    "description": "The list of team ` + "`" + `slug` + "`" + `s allowed to bypass pull request requirements.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "users": {
                    "description": "The list of user ` + "`" + `login` + "`" + `s allowed to bypass pull request requirements.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "branchprotection.ErrorResponse": {
            "type": "object",
            "properties": {
                "documentation_url": {
                    "description": "A URL to the documentation for this error.",
                    "type": "string"
                },
                "message": {
                    "description": "A message describing the error.",
                    "type": "string"
                }
            }
        },
        "branchprotection.RequiredPullRequestReviews": {
            "type": "object",
            "properties": {
                "bypass_pull_request_allowances": {
                    "description": "Allow specific users, teams, or apps to bypass pull request requirements.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.BypassAllowances"
                        }
                    ]
                },
                "dismiss_stale_reviews": {
                    "description": "Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.",
                    "type": "boolean"
                },
                "dismissal_restrictions": {
                    "description": "Specify which users, teams, and apps can dismiss pull request reviews. Pass an empty ` + "`" + `dismissal_restrictions` + "`" + ` object to disable. User and team ` + "`" + `dismissal_restrictions` + "`" + ` are only available for organization-owned repositories. Omit this parameter for personal repositories.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.UserTeamAppList"
                        }
                    ]
                },
                "require_code_owner_reviews": {
                    "description": "Blocks merging pull requests until code owners review them.",
                    "type": "boolean"
                },
                "require_last_push_approval": {
                    "description": "Whether the most recent push must be approved by someone other than the person who pushed it. Default: false.",
                    "type": "boolean",
                    "default": false
                },
                "required_approving_review_count": {
                    "description": "Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6 or 0 to not require reviewers.",
                    "type": "integer"
                }
            }
        },
        "branchprotection.RequiredPullRequestReviewsResponse": {
            "type": "object",
            "properties": {
                "bypass_pull_request_allowances": {
                    "description": "Users, teams, or apps allowed to bypass pull request requirements.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.BypassAllowances"
                        }
                    ]
                },
                "dismiss_stale_reviews": {
                    "description": "Whether approving reviews are automatically dismissed when someone pushes a new commit.",
                    "type": "boolean"
                },
                "dismissal_restrictions": {
                    "description": "Users, teams, and apps that can dismiss pull request reviews.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/branchprotection.UserTeamAppList"
                        }
                    ]
                },
                "require_code_owner_reviews": {
                    "description": "Whether merging pull requests is blocked until code owners review them.",
                    "type": "boolean"
                },
                "require_last_push_approval": {
                    "description": "Whether the most recent push must be approved by someone other than the person who pushed it.",
                    "type": "boolean"
                },
                "required_approving_review_count": {
                    "description": "The number of reviewers required to approve pull requests.",
                    "type": "integer"
                }
            }
        },
        "branchprotection.RequiredStatusChecks": {
            "type": "object",
            "required": [
                "contexts",
                "strict"
            ],
            "properties": {
                "checks": {
                    "description": "The list of status checks to require in order to merge into this branch.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/branchprotection.StatusCheck"
                    }
                },
                "contexts": {
                    "description": "\"**Closing down notice**: The list of status checks to require in order to merge into this branch. If any of these checks have recently been set by a particular GitHub App, they will be required to come from that app in future for the branch to merge. Use ` + "`" + `checks` + "`" + ` instead of ` + "`" + `contexts` + "`" + ` for more fine-grained control.\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "strict": {
                    "description": "Require branches to be up to date before merging.",
                    "type": "boolean"
                }
            }
        },
        "branchprotection.Restrictions": {
            "type": "object",
            "required": [
                "teams",
                "users"
            ],
            "properties": {
                "apps": {
                    "description": "The list of app slugs with push access.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teams": {
                    "description": "The list of team slugs with push access.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "users": {
                    "description": "The list of user logins with push access.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "branchprotection.StatusCheck": {
            "type": "object",
            "required": [
                "context"
            ],
            "properties": {
                "app_id": {
                    "description": "The ID of the GitHub App that must provide this check. Omit this field to automatically select the GitHub App that has recently provided this check, or any app if it was not set by a GitHub App. Pass -1 to explicitly allow any app to set the status.",
                    "type": "integer"
                },
                "context": {
                    "description": "The name of the required check.",
                    "type": "string"
                }
            }
        },
        "branchprotection.UserTeamAppList": {
            "type": "object",
            "properties": {
                "apps": {
                    "description": "The list of app ` + "`" + `slug` + "`" + `s with dismissal access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "teams": {
                    "description": "The list of team ` + "`" + `slug` + "`" + `s with dismissal access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "users": {
                    "description": "The list of user ` + "`" + `login` + "`" + `s with dismissal access",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.github.com",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GitHub BranchProtection Plugin API for Krateo Operator Generator (KOG)",
	Description:      "Wrapper around the GitHub Branch Protection API that normalizes response fields for consistent reconciliation in KOG.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
