package teamrepo

type TeamRepoPermissions struct {
	AllowAutoMerge      bool     `json:"allow_auto_merge"`
	AllowForking        bool     `json:"allow_forking"`
	AllowMergeCommit    bool     `json:"allow_merge_commit"`
	AllowRebaseMerge    bool     `json:"allow_rebase_merge"`
	AllowSquashMerge    bool     `json:"allow_squash_merge"`
	ArchiveURL          string   `json:"archive_url"`
	Archived            bool     `json:"archived"`
	AssigneesURL        string   `json:"assignees_url"`
	BlobsURL            string   `json:"blobs_url"`
	BranchesURL         string   `json:"branches_url"`
	CloneURL            string   `json:"clone_url"`
	CollaboratorsURL    string   `json:"collaborators_url"`
	CommentsURL         string   `json:"comments_url"`
	CommitsURL          string   `json:"commits_url"`
	CompareURL          string   `json:"compare_url"`
	ContentsURL         string   `json:"contents_url"`
	ContributorsURL     string   `json:"contributors_url"`
	CreatedAt           string   `json:"created_at"`
	DefaultBranch       string   `json:"default_branch"`
	DeleteBranchOnMerge bool     `json:"delete_branch_on_merge"`
	DeploymentsURL      string   `json:"deployments_url"`
	Description         *string  `json:"description"`
	Disabled            bool     `json:"disabled"`
	DownloadsURL        string   `json:"downloads_url"`
	EventsURL           string   `json:"events_url"`
	Fork                bool     `json:"fork"`
	Forks               int      `json:"forks"`
	ForksCount          int      `json:"forks_count"`
	ForksURL            string   `json:"forks_url"`
	FullName            string   `json:"full_name"`
	GitCommitsURL       string   `json:"git_commits_url"`
	GitRefsURL          string   `json:"git_refs_url"`
	GitTagsURL          string   `json:"git_tags_url"`
	GitURL              string   `json:"git_url"`
	HTMLURL             string   `json:"html_url"`
	HasDownloads        bool     `json:"has_downloads"`
	HasIssues           bool     `json:"has_issues"`
	HasPages            bool     `json:"has_pages"`
	HasProjects         bool     `json:"has_projects"`
	HasWiki             bool     `json:"has_wiki"`
	Homepage            *string  `json:"homepage"`
	HooksURL            string   `json:"hooks_url"`
	ID                  int      `json:"id"`
	IssueCommentURL     string   `json:"issue_comment_url"`
	IssueEventsURL      string   `json:"issue_events_url"`
	IssuesURL           string   `json:"issues_url"`
	KeysURL             string   `json:"keys_url"`
	LabelsURL           string   `json:"labels_url"`
	Language            string   `json:"language"`
	LanguagesURL        string   `json:"languages_url"`
	License             *string  `json:"license"`
	MergesURL           string   `json:"merges_url"`
	MilestonesURL       string   `json:"milestones_url"`
	MirrorURL           *string  `json:"mirror_url"`
	Name                string   `json:"name"`
	NodeID              string   `json:"node_id"`
	NotificationsURL    string   `json:"notifications_url"`
	OpenIssues          int      `json:"open_issues"`
	OpenIssuesCount     int      `json:"open_issues_count"`
	Owner               string   `json:"owner"`      // Added
	Permission          string   `json:"permission"` // Added
	Private             bool     `json:"private"`
	PullsURL            string   `json:"pulls_url"`
	PushedAt            string   `json:"pushed_at"`
	ReleasesURL         string   `json:"releases_url"`
	RoleName            string   `json:"role_name"`
	SSHURL              string   `json:"ssh_url"`
	Size                int      `json:"size"`
	StargazersCount     int      `json:"stargazers_count"`
	StargazersURL       string   `json:"stargazers_url"`
	StatusesURL         string   `json:"statuses_url"`
	SubscribersURL      string   `json:"subscribers_url"`
	SubscriptionURL     string   `json:"subscription_url"`
	SvnURL              string   `json:"svn_url"`
	TagsURL             string   `json:"tags_url"`
	TeamsURL            string   `json:"teams_url"`
	TempCloneToken      string   `json:"temp_clone_token"`
	Topics              []string `json:"topics"`
	TreesURL            string   `json:"trees_url"`
	URL                 string   `json:"url"`
	UpdatedAt           string   `json:"updated_at"`
	Visibility          string   `json:"visibility"`
	Watchers            int      `json:"watchers"`
	WatchersCount       int      `json:"watchers_count"`
}
