apiVersion: v2
name: github-provider-kog-branchprotection
description: A Helm chart for deploying the GitHub KOG BranchProtection resource.
type: application
#version: BRANCHPROTECTION_CHART_VERSION
version: 0.0.1
#appVersion: BRANCHPROTECTION_APP_VERSION

home: https://krateo.io
icon: "https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg"
keywords:
  - generator
sources:
  - https://github.com/krateoplatformops-blueprints/github-provider-kog/tree/main/github-provider-kog-branchprotection-blueprint
annotations:
  krateoSupportedVersion: ">= 2.7.0"
