# @schema
# type: object
# description: Configuration for the Collaborator Blueprint dependency.
# @schema
github-provider-kog-collaborator-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Collaborator Blueprint dependency.
  # default: true
  # @schema
  enabled: true

# @schema
# type: object
# description: Configuration for the Repo Blueprint dependency.
# @schema
github-provider-kog-repo-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Repo Blueprint dependency.
  # default: true
  # @schema
  enabled: true

# @schema
# type: object
# description: Configuration for the Runner Group Blueprint dependency.
# @schema
github-provider-kog-runnergroup-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Runner Group Blueprint dependency.
  # default: true
  # @schema
  enabled: true

# @schema
# type: object
# description: Configuration for the Team Repo Blueprint dependency.
# @schema
github-provider-kog-teamrepo-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Team Repo Blueprint dependency.
  # default: true
  # @schema
  enabled: true

# @schema
# type: object
# description: Configuration for the Workflow Blueprint dependency.
# @schema
github-provider-kog-workflow-blueprint:
  # @schema
  # type: boolean
  # description: Enable the Workflow Blueprint dependency.
  # default: true
  # @schema
  enabled: true