apiVersion: github.ogen.krateo.io/v1alpha1
kind: BranchProtection
metadata:
  name: test-branchprotection-pr-dismissal-restrictions
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  configurationRef:
    name: my-branchprotection-config
    namespace: default
  owner: krateoplatformops-test
  repo: branchprotection-tester-07
  branch: main
  enforce_admins: true
  required_status_checks:
    strict: false
    contexts: []
  required_pull_request_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    dismissal_restrictions:
      users:
        - vicentinileonardo
  restrictions:
    users: []
    teams: []
