apiVersion: github.ogen.krateo.io/v1alpha1
kind: BranchProtection
metadata:
  name: test-branchprotection-block-creations
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  configurationRef:
    name: my-branchprotection-config
    namespace: default
  owner: krateoplatformops-test
  repo: branchprotection-tester-13
  branch: main
  enforce_admins: true
  block_creations: true
  required_status_checks:
    strict: false
    contexts: []
  required_pull_request_reviews:
    required_approving_review_count: 1
  restrictions:
    users:
      - vicentinileonardo
    teams:
      - test-team
