name: blueprint-release-tag

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub App
        id: authenticate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
   
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Extract latest Chart Version
        uses: tdemin/find-latest-tag@v1
        id: chart_version
        with:
          repo: https://${{ steps.authenticate.outputs.token }}@github.com/${{ github.repository }}.git

      - name: Print Chart Version
        run: |
          echo CHART_VERSION:${{steps.chart_version.outputs.tag}}

      - name: Replace Chart Version in Chart.yaml
        run: sed -i 's/CHART_VERSION/${{ steps.chart_version.outputs.tag }}/g' ./blueprint/Chart.yaml

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ steps.authenticate.outputs.token }}
          charts_dir: ./
          charts_url: https://marketplace.krateo.io
          owner: krateoplatformops-blueprints
          repository: marketplace
          branch: gh-pages