name: plugins-source-tag

on:
  push:
    tags:
      # This workflow triggers on tags prefixed with a plugin name, e.g.,
      # collaborator-plugin/1.0.3
      # teamrepo-plugin/2.8.1
      - '*-plugin/[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-source-code:
    name: Test Source Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: "plugins/go.work.sum"
      
      - name: Run Go Tests
        run: go test -v ./pkg/... ./cmd/collaborator-plugin/... ./cmd/teamrepo-plugin/...

  parse-tag:
    name: Parse Git Tag
    needs: test-source-code
    runs-on: ubuntu-latest
    
    outputs:
      plugin: ${{ steps.parse.outputs.plugin }}
      version: ${{ steps.parse.outputs.version }}
    
    steps:
      - name: Parse Git Tag
        id: parse
        run: |
          TAG="${{ github.ref_name }}"
          PLUGIN="${TAG%%/*}"
          VERSION="${TAG##*/}"
          echo "plugin=${PLUGIN}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build-and-push-image:
    name: Build and Push Docker Image
    needs: parse-tag
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./plugins
          file: ./plugins/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/github-provider-kog/${{ needs.parse-tag.outputs.plugin }}:${{ needs.parse-tag.outputs.version }}
          build-args: |
            PLUGIN_NAME=${{ needs.parse-tag.outputs.plugin }}
