name: resource-blueprint-pullrequest

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.determine-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Determine which charts to lint
        id: determine-matrix
        run: |
          CHARTS_TO_LINT="[]"
          # List all blueprint charts, but exclude the main 'github-provider-kog-blueprint'
          ALL_CHARTS=$(ls -d github-provider-kog-*-blueprint 2>/dev/null | grep -v 'github-provider-kog-blueprint$')
          
          for chart in $ALL_CHARTS; do
            # Check if any of the changed files are within this chart's directory
            if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "$chart/"; then
              echo "Changes detected in $chart, adding to lint matrix."
              CHARTS_TO_LINT=$(echo "$CHARTS_TO_LINT" | jq -c --arg c "$chart" '. + [$c]')
            fi
          done

          echo "Charts to lint: $CHARTS_TO_LINT"
          echo "matrix={"chart":${CHARTS_TO_LINT}}" >> $GITHUB_OUTPUT

  lint-helm-charts:
    # Only run if the matrix from the previous job is not empty
    if: needs.determine-changes.outputs.matrix != '{"chart":[]}'
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.determine-changes.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0

      - name: Lint Helm Chart
        run: |
          echo "Linting chart in directory: ./${{ matrix.chart }}"
          helm lint ./${{ matrix.chart }}
